version: '3'

services:

  backend:
    container_name: kpd-backend
    build: ./backend
    env_file:
      - ./.env
    ports:
      - "4000:3007"      
    restart: always
    depends_on:
      - database
    networks:
      - backend-net

  frontend:
    container_name: kpd-frontend
    build: ./frontend
    env_file:
      - ./.env
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - backend
    networks:
      - frontend-net
  
  database:
    container_name: kpd-database
    image: postgres:12.15-alpine
    env_file:
      - ./.env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend-net

volumes:
  postgres_data:

networks:
  frontend-net:
  backend-net: