version: '3'

services:

  backend:
    container_name: 'kpd-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    networks:
      - backend-net
   
  postgres:
    container_name: 'postgres'
    image: postgres:12.15-alpine    
    restart: always
    env_file: ./backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    networks:
      - backend-net
      
  frontend:
    container_name: 'kpd-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - backend

volumes:
  pg_data:

networks:
  backend-net: