version: '3'

services:

  backend:
    container_name: kpd-backend
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"      
    restart: always
    depends_on:
      - kupipodariday
    networks:
      - backend-net

  frontend:
    container_name: kpd-frontend
    build: ./frontend
    env_file:
      - ./backend/.env
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - backend
    networks:
      - frontend-net
  
  kupipodariday:
    container_name: kupipodariday
    image: postgres:12.15-alpine
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend-net

volumes:
  postgres_data:

networks:
  frontend-net:
  backend-net: